baseURL: 'https://tanishiking.github.io/'
languageCode: 'en-us'
paginate: 10
title: 'Rikito Taniguchi'
theme: "PaperMod"
params:
    ShowBreadCrumbs: true
    defaultTheme: light
    ShowShareButtons: false
    ShowToc: true
    homeInfoParams:
        Title: About
        Content: |-
          Hi, I'm Rikito Taniguchi. Master's student of Computer Science at Tokyo Institute of Technology.
          You'll find me working on developer tooling especially in Scala, studying programming language theory, or Web development.

    socialIcons:
        - name: github
          url: "https://github.com/tanishiking"
        - name: twitter
          url: "https://twitter.com/tanishiking25"
        - name: linkedin
          url: "https://www.linkedin.com/in/rikito-taniguchi-8b372b175/"
        - name: email
          url: "rikiriki1238@gmail.com"
menu:
    main:
        - identifier: cv
          name: CV
          url: /cv/
          weight: 10
        - identifier: ags
          name: Tags
          url: /tags/
          weight: 10
