baseURL = "https://tanishiking.github.io/"
languageCode = "en-us"
paginate = 10
title = "Rikito Taniguchi"

[module]
  [[module.imports]]
    path = "github.com/nanxiaobei/hugo-paper"

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'tanishiking25'               # twitter.com/YOUR_TWITTER_ID
  github = 'tanishiking'                 # github.com/YOUR_GITHUB_ID
  instagram = 'rikitotaniguchi'           # instagram.com/YOUR_INSTAGRAM_ID
  linkedin = 'rikito-taniguchi-8b372b175'             # linkedin.com/in/YOUR_LINKEDIN_ID
  # mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'
  rss = true                                # show rss icon

  # home page profile
  avatar = 'rikiriki1238@gmail.com'                 # gravatar email or image url
  name = 'Rikito Taniguchi'
  bio = 'Scala Compiler Engineer based in Japan'
