baseURL: https://tanishiking.github.io/
languageCode: en-us
title: tanishiking blog
theme: hugo-theme-mini
pagination:
  pagerSize: 10

# fork for https://github.com/nodejh/hugo-theme-mini/issues/167
theme: 
   - github.com/tanishiking/hugo-theme-mini

hasCJKLanguage: true
permalinks:
  posts: /posts/:title/

# googleAnalytics: UA-123-45
# disqusShortname: nodejh

markup:
  highlight:
    guessSyntax: true
    style: emacs

params:
  author: tanishiking
  bio: Scala Compiler Engineer
  description: Rikito Taniguchi's website
  enableRSS: false
  enableComments: false
  enableGoogleAnalytics: false
  social:
    github: https://github.com/tanishiking
    twitter: https://twitter.com/tanishiking25
    linkedin: https://www.linkedin.com/in/rikitotaniguchi/


