baseURL = "https://tanishiking.github.io/"
languageCode = "en-us"
paginate = 10
title = "Rikito Taniguchi"

[module]
  [[module.imports]]
    path = 'github.com/alex-shpak/hugo-book'

[params]
  BookSearch = false
  BookTheme = 'auto'
